1:
  x: -6.0
  y: -6.0
2:
  x: -2.0
  y: -6.0
3:
  x: 2.0
  y: -6.0
4:
  x: 6.0
  y: -6.0
5:
  x: -6.0
  y: -2.0
6:
  x: -2.0
  y: -2.0
7:
  x: 2.0
  y: -2.0
8:
  x: 6.0
  y: -2.0
9:
  x: -6.0
  y: 2.0
10:
  x: -2.0
  y: 2.0
11:
  x: 2.0
  y: 2.0
12:
  x: 6.0
  y: 2.0
13:
  x: -6.0
  y: 6.0
14:
  x: -2.0
  y: 6.0
15:
  x: 2.0
  y: 6.0
16:
  x: 6.0
  y: 6.0
