transform_tolerance: 0.2

always_send_full_costmap: false

footprint: [[0.20, 0.125], [0.20, -0.125], [-0.20, -0.125], [-0.20, 0.125]]


static_layer:
  unknown_cost_value: -1
  lethal_cost_threshold: 254
  first_map_only: true
  subscribe_to_updates: false
  track_unknown_space: true
  use_maximum: true
  trinary_costmap: true


laser_scan_obstacle_layer:
  observation_sources: laser_scan 

  track_unknown_space: true
  footprint_clearing_enabled: true
  combination_method: 1  # 0 - overwrite, 1 - max, 99 - nothing

  laser_scan: 
    sensor_frame: $(arg robot)/laser_scanner_link
    data_type: LaserScan
    topic: /$(arg robot)/sensors/laser_scanner/scan_raw
    marking: true
    clearing: true
    obstacle_range: 24.5
    raytrace_range: 25.
    inf_is_valid: true

holocamera_obstacle_layer:
    observation_sources: point_cloud_holocamera
    track_unknown_space: true
    footprint_clearing_enabled: true
    
    point_cloud_holocamera:
        sensor_frame: ""
        data_type: PointCloud2
        topic: /$(arg robot)/sensors/holocamera/depth_registered/points
        marking: true
        clearing: true
        min_obstacle_height: 0.2
        max_obstacle_height: 1.5
        obstacle_range: 10.0
        raytrace_range: 12.0      
        
inflation_layer:
  inflation_radius: 20.  # the bigger the better, defines where the gradient is
  cost_scaling_factor: 1. # the bigger the steeper the gradient is


