global_costmap:
  global_frame: map
  robot_base_frame: $(arg robot)/base_link

  always_send_full_costmap: false
  rolling_window: false

  update_frequency: 5.
  publish_frequency: 2.

  plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
    - {name: laser_scan_obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    #- {name: primary_camera_obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

