local_costmap:
  global_frame: odom
  #global_frame: map
  robot_base_frame: base_link

  always_send_full_costmap: false
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.1

  update_frequency: 5.
  publish_frequency: 2.
  
  plugins:
  - {name: static_layer, type: "costmap_2d::StaticLayer"}
  #- {name: sonar_sensor_layer, type: 'range_sensor_layer::RangeSensorLayer'}
  - {name: laser_scan_obstacle_layer, type: "costmap_2d::ObstacleLayer"}
  - {name: holocamera_obstacle_layer, type: "costmap_2d::ObstacleLayer"}
  - {name: back_camera_obstacle_layer, type: "costmap_2d::ObstacleLayer"}    
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

