<?xml version="1.0" encoding="utf-8"?>
<!-- This URDF was automatically created by SolidWorks to URDF Exporter! Originally created by Stephen Brawner (brawner@gmail.com) 
     Commit Version: 1.6.0-1-g15f4949  Build Version: 1.6.7594.29634
     For more information, please see http://wiki.ros.org/sw_urdf_exporter -->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="mse6">
    
  <xacro:arg name="robot" default="mse6-XXXXX"/>
    
  <xacro:include filename="$(find mse6_description)/urdf/mse6.gazebo"/>
    
  <xacro:property name="wheel_r" value="0.025"/>  
  <xacro:property name="wheel_h" value="0.030"/>
  
  <xacro:property name="steer_limit" value="0.5"/>
  
  <link name="$(arg robot)/base_link"/>
  
  <!-- SENSORS -->
  
  <link name="$(arg robot)/laser_scanner_link">
      
    <!--<collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>        
          <box size="0.4 0.15 0.3" />
      </geometry>
    </collision>-->
  </link>
  
  <joint name="$(arg robot)/laser_scanner_j"
         type="fixed">
      <parent link="$(arg robot)/base_link"/>
      <child link="$(arg robot)/laser_scanner_link"/>
      <origin
          xyz="0.1 0 0.07"
          rpy="0 0 0"/>
  </joint>
  
  <link name="$(arg robot)/holocamera_link"/>
  
  <joint name="$(arg robot)/holocamera_j"
         type="fixed">
      <parent link="$(arg robot)/base_link"/>
      <child link="$(arg robot)/holocamera_link"/>
      <origin
          xyz="0.19 0 0.07"
          rpy="0 0 0"/>
  </joint>
  
  <link name="$(arg robot)/holocamera_optical_link"/>
  
  <joint name="$(arg robot)/holocamera_optical_j"
         type="fixed">
      <parent link="$(arg robot)/holocamera_link"/>
      <child link="$(arg robot)/holocamera_optical_link"/>
      <origin
          xyz="0 0 0"
          rpy="${-pi/2} 0 ${-pi/2}"/>
  </joint>

  <!-- Rangefinders (sonar) -->
  <xacro:include filename="$(find mse6_description)/urdf/rangefinders.xacro"/>

  <!-- BODY -->
  
  <joint name="$(arg robot)/body_bott_link_j"
         type="fixed">
      <parent link="$(arg robot)/base_link"/>
      <child link="$(arg robot)/body_bott_link"/>
      <origin
          xyz = "0 0 0.055"
          rpy="0 0 ${pi}"/>
  </joint>

  <link
    name="$(arg robot)/body_bott_link">
    <inertial>
      <origin
        xyz="-0.0122155028263459 -4.96658397779976E-08 -0.00438944402790101"
        rpy="0 0 0" />
      <mass
        value="0.669776829617329" />
      <inertia
        ixx="0.00539268235460428"
        ixy="-1.35829186636467E-08"
        ixz="8.340914352775E-05"
        iyy="0.013420683457625"
        iyz="-3.04908606084847E-09"
        izz="0.0186360064602886" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://mse6_description/meshes/body_bott_link.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.792156862745098 0.819607843137255 0.933333333333333 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://mse6_description/meshes/body_bott_link.STL" />
          <!--<box size="0.4 0.15 0.3" />-->
      </geometry>
    </collision>
  </link>
  
  <link
    name="$(arg robot)/body_upper_link">
    <inertial>
      <origin
        xyz="0.0106523635822384 0.0957583223773372 7.70065903718291E-07"
        rpy="0 0 0" />
      <mass
        value="3.31897594877579" />
      <inertia
        ixx="0.0322670587324957"
        ixy="-0.00197272153001404"
        ixz="4.43741515523342E-08"
        iyy="0.0616233997912911"
        iyz="1.63446488019635E-07"
        izz="0.0545208392676588" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://mse6_description/meshes/body_upper_link.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.792156862745098 0.819607843137255 0.933333333333333 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://mse6_description/meshes/body_upper_link.STL" />
      </geometry>
    </collision>
  </link>
  
  <joint
    name="$(arg robot)/body_bottom_j"
    type="fixed">
    <origin
      xyz="0 0 0.024"
      rpy="1.5707963267949 0 0" />
    <parent
      link="$(arg robot)/body_bott_link" />
    <child
      link="$(arg robot)/body_upper_link" />
    <axis
      xyz="0 0 0" />
  </joint>
  
  <!-- FAKE FORWARD WHEEL -->
  
  <link name="$(arg robot)/fake_fwd_wheel_link"/>
  
  <joint name="$(arg robot)/fake_fwd_wheel_j" type="revolute">
      <parent link="$(arg robot)/body_upper_link"/>
      <child link="$(arg robot)/fake_fwd_wheel_link"/>
      <origin
          xyz="-0.1 -0.054 0"
          rpy="${pi/2} 0 ${pi}"
          />
      <axis xyz="0 1 0"/>
      
      <limit
        lower="${-steer_limit}"
        upper="${steer_limit}"
        effort="0.5"
        velocity="0.5" />
      
    </joint>
  
  <!-- FORWARD LEFT WHEEL -->

  <link
    name="$(arg robot)/fwd_left_wheel_holder_link">
    <inertial>
      <origin
        xyz="0 0.00371724710345012 0.0124491235899492"
        rpy="0 0 0" />
      <mass
        value="0.0211931028009629" />
      <inertia
        ixx="3.53229576994219E-06"
        ixy="-3.11019910319938E-22"
        ixz="2.36573655190166E-22"
        iyy="3.30604049675199E-06"
        iyz="1.92941956416194E-07"
        izz="3.06173646956124E-06" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://mse6_description/meshes/fwd_left_wheel_holder_link.STL" />
      </geometry>
      <material
        name="">

        <color
          rgba="0.792156862745098 0.819607843137255 0.933333333333333 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://mse6_description/meshes/fwd_left_wheel_holder_link.STL" />
      </geometry>
    </collision>
  </link>
  
  <joint
    name="$(arg robot)/fwd_left_wheel_holder_j"
    type="revolute">
    <origin
      xyz="-0.1 -0.054 0.065"
      rpy="0 0 0.035451" />
    <parent
      link="$(arg robot)/body_upper_link" />
    <child
      link="$(arg robot)/fwd_left_wheel_holder_link" />
    <axis
      xyz="0 1 0" />
    <limit
      lower="${-steer_limit}"
      upper="${steer_limit}"
      effort="0.5"
      velocity="0.5" />
    <dynamics
      damping="0.01"
      friction="0.05" />
  </joint>
  
  <link
    name="$(arg robot)/fwd_left_wheel_link">
    <inertial>
      <origin
        xyz="7.49757243442839E-09 0.0140446440204255 -1.20170077361204E-08"
        rpy="0 0 0" />
      <mass
        value="0.051765802678868" />
      <inertia
        ixx="1.23841652921864E-05"
        ixy="-4.39731323252349E-12"
        ixz="-1.01190667024014E-11"
        iyy="1.76432330584378E-05"
        iyz="8.24926177913857E-12"
        izz="1.23842195690004E-05" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://mse6_description/meshes/fwd_left_wheel_link.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.792156862745098 0.819607843137255 0.933333333333333 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 ${wheel_h/2} 0"
        rpy="${pi/2} 0 0" />
      <geometry>
        <!--<mesh
          filename="package://mse6_description/meshes/fwd_left_wheel_link.STL" />-->
          <cylinder length="${wheel_h}" radius="${wheel_r}"/>          
      </geometry>      
    </collision>
  </link>
  
  <joint
    name="$(arg robot)/fwd_left_wheel_j"
    type="continuous">
    <origin
      xyz="0 0 0.03"
      rpy="1.5708 0 1.5353" />
    <parent
      link="$(arg robot)/fwd_left_wheel_holder_link" />
    <child
      link="$(arg robot)/fwd_left_wheel_link" />
    <axis
      xyz="0 -1 0" />
    <dynamics
      damping="0.05"
      friction="0.01" />
  </joint>
  
  <transmission name="$(arg robot)/tran_fwd_left_steer">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="$(arg robot)/fwd_left_wheel_holder_j">
        <hardwareInterface>VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="$(arg robot)/fwd_left_steer">
        <hardwareInterface>VelocityJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  
  <!--<transmission name="tran_fwd_left">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="fwd_left_wheel_j">
        <hardwareInterface>VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="fwd_left">
        <hardwareInterface>VelocityJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>-->
  
  <!-- FORWARD RIGHT WHEEL -->

  <link
    name="$(arg robot)/fwd_right_wheel_holder_link">
    <inertial>
      <origin
        xyz="1.38777878078145E-17 0.00371724710345012 0.00244912358994914"
        rpy="0 0 0" />
      <mass
        value="0.0211931028009629" />
      <inertia
        ixx="3.53229576994218E-06"
        ixy="-1.0977341764353E-22"
        ixz="-1.87522225797809E-22"
        iyy="3.30604049675198E-06"
        iyz="1.92941956416194E-07"
        izz="3.06173646956124E-06" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://mse6_description/meshes/fwd_right_wheel_holder_link.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.792156862745098 0.819607843137255 0.933333333333333 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://mse6_description/meshes/fwd_right_wheel_holder_link.STL" />
      </geometry>
    </collision>
  </link>
  
  <joint
    name="$(arg robot)/fwd_right_wheel_holder_j"
    type="revolute">
    <origin
      xyz="-0.1 -0.054 -0.075"
      rpy="3.1416 0 3.1416" />
    <parent
      link="$(arg robot)/body_upper_link" />
    <child
      link="$(arg robot)/fwd_right_wheel_holder_link" />
    <axis
      xyz="0 1 0" />
    <limit
      lower="-0.5"
      upper="0.5"
      effort="0.5"
      velocity="0.5" />
    <dynamics
      damping="0.01"
      friction="0.05" />
  </joint>
  
  <link
    name="$(arg robot)/fwd_right_wheel_link">
    <inertial>
      <origin
        xyz="7.49757245177562E-09 0.0140446440204255 -1.20170077083648E-08"
        rpy="0 0 0" />
      <mass
        value="0.051765802678868" />
      <inertia
        ixx="1.23841652921864E-05"
        ixy="-4.39731322971975E-12"
        ixz="-1.01190667028144E-11"
        iyy="1.76432330584378E-05"
        iyz="8.2492617790428E-12"
        izz="1.23842195690004E-05" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://mse6_description/meshes/fwd_right_wheel_link.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.792156862745098 0.819607843137255 0.933333333333333 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 ${wheel_h/2} 0"
        rpy="${pi/2} 0 0" />
      <geometry>
        <!--<mesh
          filename="package://mse6_description/meshes/fwd_left_wheel_link.STL" />-->
          <cylinder length="${wheel_h}" radius="${wheel_r}"/>          
      </geometry>
    </collision>
  </link>
  
  <joint
    name="$(arg robot)/fwd_right_wheel_j"
    type="continuous">
    <origin
      xyz="0 0 0.02"
      rpy="1.5708 0 3.1416" />
    <parent
      link="$(arg robot)/fwd_right_wheel_holder_link" />
    <child
      link="$(arg robot)/fwd_right_wheel_link" />
    <axis
      xyz="0 1 0" />
    <dynamics
      damping="0.05"
      friction="0.01" />
  </joint>
  
  <transmission name="$(arg robot)/tran_fwd_right_steer">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="$(arg robot)/fwd_right_wheel_holder_j">
        <hardwareInterface>VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="$(arg robot)/fwd_right_steer">
        <hardwareInterface>VelocityJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  
  <!--<transmission name="tran_fwd_right">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="fwd_right_wheel_j">
        <hardwareInterface>VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="fwd_right">
        <hardwareInterface>VelocityJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>-->
  
  <!-- FAKE BACK LINK -->
  
  <link name="$(arg robot)/fake_back_wheel_link"/>
  
  <joint name="$(arg robot)/fake_back_wheel_j" type="continuous">
         <origin 
             xyz="0.1 -0.054 0.0"
             rpy="${pi/2} 0 ${pi}"/>
         <parent link="$(arg robot)/body_upper_link"/>
         <child link="$(arg robot)/fake_back_wheel_link"/>
         <axis xyz="0 1 0"/>
     </joint>
  
  <!-- BACK LEFT WHEEL -->
  
  <link
    name="$(arg robot)/back_left_wheel_holder_link">
    <inertial>
      <origin
        xyz="-1.38777878078145E-17 0.00371724710345012 0.00244912358994914"
        rpy="0 0 0" />
      <mass
        value="0.0211931028009629" />
      <inertia
        ixx="3.53229576994218E-06"
        ixy="-1.3305004692995E-22"
        ixz="2.88569550200515E-22"
        iyy="3.30604049675198E-06"
        iyz="1.92941956416194E-07"
        izz="3.06173646956124E-06" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://mse6_description/meshes/back_left_wheel_holder_link.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.792156862745098 0.819607843137255 0.933333333333333 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://mse6_description/meshes/back_left_wheel_holder_link.STL" />
      </geometry>
    </collision>
  </link>
  
  <joint
    name="$(arg robot)/back_left_wheel_holder_j"
    type="fixed">
    <origin
      xyz="0.1 -0.054 0.075"
      rpy="0 0 0" />
    <parent
      link="$(arg robot)/body_upper_link" />
    <child
      link="$(arg robot)/back_left_wheel_holder_link" />
    <axis
      xyz="0 0 0" />
  </joint>
  
  <link
    name="$(arg robot)/back_left_wheel_link">
    <inertial>
      <origin
        xyz="7.49757243789784E-09 0.0140446440204255 -1.20170077153037E-08"
        rpy="0 0 0" />
      <mass
        value="0.051765802678868" />
      <inertia
        ixx="1.23841652921864E-05"
        ixy="-4.39731323173739E-12"
        ixz="-1.01190667019079E-11"
        iyy="1.76432330584378E-05"
        iyz="8.24926178262453E-12"
        izz="1.23842195690005E-05" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://mse6_description/meshes/back_left_wheel_link.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.792156862745098 0.819607843137255 0.933333333333333 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 ${wheel_h/2} 0"
        rpy="${pi/2} 0 0" />
      <geometry>
        <!--<mesh
          filename="package://mse6_description/meshes/fwd_left_wheel_link.STL" />-->
          <cylinder length="${wheel_h}" radius="${wheel_r}"/>          
      </geometry>
    </collision>
  </link>
  
  <joint
    name="$(arg robot)/back_left_wheel_j"
    type="continuous">
    <origin
      xyz="0 0 0.02"
      rpy="1.5708 0 0" />
    <parent
      link="$(arg robot)/back_left_wheel_holder_link" />
    <child
      link="$(arg robot)/back_left_wheel_link" />
    <axis
      xyz="0 1 0" />
    <dynamics
      damping="0.01"
      friction="0.05" />
  </joint>
  
  <transmission name="$(arg robot)/tran_back_left">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="$(arg robot)/back_left_wheel_j">
        <hardwareInterface>VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="$(arg robot)/back_left">
        <hardwareInterface>VelocityJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  
  <transmission name="$(arg robot)/tran1">
      <type>transmission_interface/SimpleTransmission</type>
        <joint name="$(arg robot)/back_left_wheel_j">
          <hardwareInterface>EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="$(arg robot)/motor1">
          <hardwareInterface>EffortJointInterface</hardwareInterface>
          <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>
  
  <!-- BACK RIGHT WHEEL -->
  
  <link
    name="$(arg robot)/back_right_wheel_holder_link">
    <inertial>
      <origin
        xyz="-1.38777878078145E-17 0.00371724710345012 0.00244912358994917"
        rpy="0 0 0" />
      <mass
        value="0.0211931028009629" />
      <inertia
        ixx="3.53229576994219E-06"
        ixy="2.11005131993304E-22"
        ixz="-3.28467007444202E-23"
        iyy="3.30604049675199E-06"
        iyz="1.92941956416194E-07"
        izz="3.06173646956124E-06" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://mse6_description/meshes/back_right_wheel_holder_link.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.792156862745098 0.819607843137255 0.933333333333333 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://mse6_description/meshes/back_right_wheel_holder_link.STL" />
      </geometry>
    </collision>
  </link>
  
  <joint
    name="$(arg robot)/back_right_wheel_holder_j"
    type="fixed">
    <origin
      xyz="0.1 -0.054 -0.075"
      rpy="3.1416 0 3.1416" />
    <parent
      link="$(arg robot)/body_upper_link" />
    <child
      link="$(arg robot)/back_right_wheel_holder_link" />
    <axis
      xyz="0 0 0" />
  </joint>
  
  <link
    name="$(arg robot)/back_right_wheel_link">
    <inertial>
      <origin
        xyz="7.49757243789784E-09 0.0140446440204255 -1.20170077222426E-08"
        rpy="0 0 0" />
      <mass
        value="0.051765802678868" />
      <inertia
        ixx="1.23841652921864E-05"
        ixy="-4.39731323051131E-12"
        ixz="-1.01190667027069E-11"
        iyy="1.76432330584378E-05"
        iyz="8.24926178070993E-12"
        izz="1.23842195690004E-05" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://mse6_description/meshes/back_right_wheel_link.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.792156862745098 0.819607843137255 0.933333333333333 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 ${wheel_h/2} 0"
        rpy="${pi/2} 0 0" />
      <geometry>
        <!--<mesh
          filename="package://mse6_description/meshes/fwd_left_wheel_link.STL" />-->
          <cylinder length="${wheel_h}" radius="${wheel_r}"/>          
      </geometry>
    </collision>
  </link>
  
  <joint
    name="$(arg robot)/back_right_wheel_j"
    type="continuous">
    <origin
      xyz="0 0 0.02"
      rpy="1.5708 0 1.5708" />
    <parent
      link="$(arg robot)/back_right_wheel_holder_link" />
    <child
      link="$(arg robot)/back_right_wheel_link" />
    <axis
      xyz="0 -1 0" />
    <dynamics
      damping="0.01"
      friction="0.05" />
  </joint>
  
  <transmission name="$(arg robot)/tran_back_right">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="$(arg robot)/back_right_wheel_j">
        <hardwareInterface>VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="$(arg robot)/back_right">
        <hardwareInterface>VelocityJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  
  <transmission name="$(arg robot)/tran2">
      <type>transmission_interface/SimpleTransmission</type>
        <joint name="$(arg robot)/back_right_wheel_j">
          <hardwareInterface>EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="$(arg robot)/motor2">
          <hardwareInterface>EffortJointInterface</hardwareInterface>
          <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <!--<gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace></robotNamespace>
      <robotSimType>steer_bot_hardware_gazebo/SteerBotHardwareGazebo</robotSimType>
      
    </plugin>
  </gazebo>-->
    
</robot>
